# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Copy dependencies
      run: |
        mvn dependency:copy-dependencies -DoutputDirectory=./lib
        mkdir publish
        mv *.jar ./publish
        mv dockerfile ./publish
        mv lib ./publish

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Publish
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:0niros/wxRobot-0nion-publish.git
        BRANCH: master
        FOLDER: publish
        SSH_PRIVATE_KEY: ${{ secrets.ACTION_DEPLOY_SECRET }}
        CLEAR_GLOBS_FILE: ".clear-target-files"
